all: prep run clean

prep:
	@echo "This is Lane 1." > ./ex.dat
	@echo "This is aL1ne 1." > ./ex.dat
	@echo "This also is lbne 1." >> ./ex.dat
	@echo "This is Laane 1." >> ./ex.dat
	@echo "This is Labne 1." >> ./ex.dat
	@echo "This is Lbne 1." >> ./ex.dat
	@echo "This is Lcne 1." >> ./ex.dat
	@echo "This is Ldne 1." >> ./ex.dat
	@echo "This is Lene 1." >> ./ex.dat
	@echo "This is Lfne 1." >> ./ex.dat
	@echo "This is ne 1." >> ./ex.dat
	
run: ex.sh
	./ex.sh

clean:
	@rm -f ./ex.dat
