#
# TARGET:	<list of dependencies>
# <tab>	Action/Rule Lines
# <tab>	Action/Rule Lines
# <tab>	Action/Rule Lines
# <tab>	Action/Rule Lines
#

dbg: ex1 clean

ex1: ex1.c ex1a.c ex1.h
	gcc -o ex1 ex1.c ex1a.c

clean:
	rm -f ex1 ex1.o ex1a.o
