all: run clean

run: prep
	@echo "<<<<<<<<<<<<<<<<<<<<<<<  >>>>>>>>>>>>>>>>>>>>>>>"
	-./ls3 			# No argument needed
	@echo "<<<<<<<<<<<<<<<<<<<<<<<  >>>>>>>>>>>>>>>>>>>>>>>"

prep: ls3

ls3: ls3.c

clean:
	rm -f ls?




