all: run clean

run: ex1 ex1app
	-@chmod +x ./ex.sh
	@echo "#############################"
	./ex1 app
	@echo "#############################"
	./ex1 sh
	@echo "#############################"

clean:
	rm -f ex? ex1app
