all: prep run clean

prep:
	@echo "This is Lane 1." > ./ex.dat
	@echo "This is La1ne 1." > ./ex.dat
	@echo "This is aL1ne 1." > ./ex.dat
	@echo "This also is lbne 1." >> ./ex.dat
	@echo "This is Lcne 1." >> ./ex.dat
	@echo "This is Ldne 1." >> ./ex.dat
	@echo "This is Lene 1." >> ./ex.dat
	@echo "This is Lfne 1." >> ./ex.dat
	@echo "This is Lgne 1." >> ./ex.dat
	@echo "This is Lhne 1." >> ./ex.dat
	@echo "This is Line 1." >> ./ex.dat
	
run: ex.sh
	./ex.sh

clean:
	@rm -f ./ex.dat
