all: run clean

run: prep
#	cat praveen-assignment-15-input.doc
	./praveen-assignment-15
#	cat praveen-assignment-15-output.doc

prep: praveen-assignment-15 

praveen-assignment-15: praveen-assignment-15.c 

clean:
	rm -f praveen-assignment-15
