all: run clean

run: prep
#	cat praveen-assignment-17-input.doc
	./praveen-assignment-17
	cat praveen-assignment-17-output.doc

prep: praveen-assignment-17 

praveen-assignment-17: praveen-assignment-17.c stack.c

clean:
	rm -f praveen-assignment-17
