all: run clean

run: prep
	cat praveen-assignment-14-input.doc
	./praveen-assignment-14
	cat praveen-assignment-14-output.doc

prep: praveen-assignment-14 

praveen-assignment-14: praveen-assignment-14.c 

clean:
	rm -f praveen-assignment-14
