all: run clean

run: prep
	cat praveen-assignment-13-input.doc
	./praveen-assignment-13
	cat praveen-assignment-13-output.doc

prep: praveen-assignment-13 

praveen-assignment-13: praveen-assignment-13.c binaryTree.c

clean:
	rm -f praveen-assignment-13
