all: run clean

run: prep
	cat praveen-assignment-12-input.doc
	./praveen-assignment-12
	cat praveen-assignment-12-output.doc

prep: praveen-assignment-12 

praveen-assignment-12: praveen-assignment-12.c 

clean:
	rm -f praveen-assignment-12
